name: flutter_precommit_refactor
description: A Dart CLI tool for setting up pre-commit hooks in Flutter projects.
version: 1.0.0+1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

executables:
  fpr: fpr

# Add regular dependencies here.
dependencies:
  process_run: ^0.12.0
  yaml: ^3.1.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
